<a href="https://colab.research.google.com/github/Keistkmiya/Tugas2-MachineLearning/blob/main/Tugas2_Chapter2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Chapter 2: Loading Data

##Setup and Library Imports

In [1]:
import pandas as pd
import numpy as np

print(f"Pandas version: {pd.__version__}")
print(f"NumPy version: {np.__version__}")

Pandas version: 2.2.2
NumPy version: 2.0.2

## Loading a CSV File

CSV (*Comma Separated Values*) adalah format file yang paling umum kita temui dalam analisis data. Pandas mempermudah kita untuk memuat file ini menjadi sebuah objek yang disebut **DataFrame**. DataFrame ini bisa kita bayangkan seperti tabel di spreadsheet (Excel), namun dengan kekuatan pemrosesan Python yang jauh lebih cepat.

In [3]:
url_ev = "https://data.wa.gov/api/views/f6w7-q2d2/rows.csv?accessType=DOWNLOAD"
df_ev = pd.read_csv(url_ev)

print("Data Kendaraan Listrik (5 baris teratas):")
display(df_ev.head())

print(f"\nTotal data yang dimuat: {len(df_ev)} baris.")

Data Kendaraan Listrik (5 baris teratas):

,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Legislative District,DOL Vehicle ID,Vehicle Location,Electric Utility,2020 Census Tract
0,1N4AZ0CP6D,King,Kirkland,WA,98034.0,2013,NISSAN,LEAF,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,75.0,1.0,154635729,POINT (-122.22901 47.72201),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),5.303302e+10
1,5YJ3E1EC8L,Kitsap,Bainbridge Island,WA,98110.0,2020,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,308.0,23.0,107518645,POINT (-122.521 47.62759),PUGET SOUND ENERGY INC,5.303509e+10
2,5YJ3E1EBXJ,King,Seattle,WA,98144.0,2018,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,215.0,37.0,474808813,POINT (-122.30866 47.57874),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303301e+10
3,ZFAFFAC45R,Thurston,Yelm,WA,98597.0,2024,FIAT,500E,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,2.0,273658514,POINT (-122.60735 46.94239),PUGET SOUND ENERGY INC,5.306701e+10
4,5YJYGDEE3L,King,Kent,WA,98030.0,2020,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,291.0,47.0,109579900,POINT (-122.19975 47.37483),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),5.303303e+10

Total data yang dimuat: 280833 baris.

## Loading a JSON File

JSON adalah format yang sangat ringan dan sering digunakan untuk pengiriman data antar aplikasi web. Struktur JSON biasanya berbentuk seperti kamus (*dictionary*) di Python dengan pasangan kunci dan nilai (key-value pairs). Pandas memudahkan kita untuk mengubah struktur yang bersifat hierarkis ini menjadi tabel DataFrame yang rapi.

In [4]:
url_json = "https://raw.githubusercontent.com/domoritz/maps/master/data/iris.json"

df_json = pd.read_json(url_json)

print("Data Iris dari format JSON:")
display(df_json.head())

Data Iris dari format JSON:

   sepalLength  sepalWidth  petalLength  petalWidth species
0          5.1         3.5          1.4         0.2  setosa
1          4.9         3.0          1.4         0.2  setosa
2          4.7         3.2          1.3         0.2  setosa
3          4.6         3.1          1.5         0.2  setosa
4          5.0         3.6          1.4         0.2  setosa

## Querying a SQL Database

Di dunia industri, data sering kali tidak disimpan dalam file satuan, melainkan di dalam database. Untuk mengambilnya, kita bisa menggunakan bahasa SQL. Pandas memiliki fungsi `read_sql_query` yang sangat kuat untuk menarik data langsung dari database ke dalam DataFrame kita.

Sebagai contoh, kita akan membuat database sementara di memori menggunakan `sqlite3` untuk mensimulasikan proses ini.

In [5]:
import sqlite3

conn = sqlite3.connect(":memory:")
df_ev.head(100).to_sql("ev_table", conn)
query = "SELECT City, Make, Model FROM ev_table WHERE Make = 'TESLA'"
df_tesla = pd.read_sql_query(query, conn)

print("Hasil Filter SQL (Hanya mobil Tesla):")
display(df_tesla.head())

Hasil Filter SQL (Hanya mobil Tesla):

                City   Make    Model
0  Bainbridge Island  TESLA  MODEL 3
1            Seattle  TESLA  MODEL 3
2               Kent  TESLA  MODEL Y
3            Seattle  TESLA  MODEL X
4           Kirkland  TESLA  MODEL 3

## Describing the Data

Setelah kita berhasil memuat data, langkah selanjutnya adalah melakukan eksplorasi dasar. Kita perlu memahami struktur data, tipe data di setiap kolom, serta statistik deskriptifnya. Ini akan membantu kita mengidentifikasi apakah ada keanehan pada data (seperti nilai yang hilang atau *outlier*) sebelum kita melangkah ke tahap analisis yang lebih dalam.

Kita akan menggunakan tiga fungsi utama dari Pandas untuk "mengintip" data kita:
1. `shape`: Untuk melihat dimensi (jumlah baris dan kolom).
2. `info()`: Untuk melihat tipe data dan memori yang digunakan.
3. `describe()`: Untuk melihat statistik ringkasan seperti rata-rata, nilai minimum, dan maksimum.

In [6]:
print("Dimensi Data (Baris, Kolom):", df_ev.shape)

print("\nInformasi Struktur Data:")
df_ev.info()

print("\nStatistik Deskriptif Data:")
display(df_ev.describe())

Dimensi Data (Baris, Kolom): (280833, 16)

Informasi Struktur Data:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 280833 entries, 0 to 280832
Data columns (total 16 columns):
 #   Column                                             Non-Null Count   Dtype
---  ------                                             --------------   -----
 0   VIN (1-10)                                         280833 non-null  object
 1   County                                             280821 non-null  object
 2   City                                               280821 non-null  object
 3   State                                              280833 non-null  object
 4   Postal Code                                        280821 non-null  float64
 5   Model Year                                         280833 non-null  int64
 6   Make                                               280833 non-null  object
 7   Model                                              280833 non-null  object
 8   Electric Vehicle Type                              280833 non-null  object
 9   Clean Alternative Fuel Vehicle (CAFV) Eligibility  280833 non-null  object
 10  Electric Range                                     280821 non-null  float64
 11  Legislative District                               280130 non-null  float64
 12  DOL Vehicle ID                                     280833 non-null  int64
 13  Vehicle Location                                   280813 non-null  object
 14  Electric Utility                                   280821 non-null  object
 15  2020 Census Tract                                  280821 non-null  float64
dtypes: float64(4), int64(2), object(10)
memory usage: 34.3+ MB

Statistik Deskriptif Data:

,Postal Code,Model Year,Electric Range,Legislative District,DOL Vehicle ID,2020 Census Tract
count,280821.000000,280833.000000,280821.000000,280130.000000,2.808330e+05,2.808210e+05
mean,98175.409538,2022.111643,38.757846,28.819352,2.470600e+08,5.297039e+10
std,2591.070456,3.064528,77.903581,14.907410,6.325326e+07,1.654845e+09
min,1030.000000,1999.000000,0.000000,1.000000,4.385000e+03,1.001020e+09
25%,98052.000000,2021.000000,0.000000,17.000000,2.240730e+08,5.303301e+10
50%,98133.000000,2023.000000,0.000000,32.000000,2.642395e+08,5.303303e+10
75%,98382.000000,2024.000000,32.000000,42.000000,2.803006e+08,5.305394e+10
max,99517.000000,2027.000000,337.000000,49.000000,4.791150e+08,6.601095e+10

## Navigating DataFrames

Untuk menavigasi atau mengambil bagian tertentu dari data, kita memiliki dua metode utama di Pandas:

1. **iloc**: Digunakan jika kita ingin mengambil data berdasarkan **posisi indeksnya** (berupa angka). Ini sangat berguna jika kita ingin melakukan *slicing* seperti pada list Python biasa.
2. **loc**: Digunakan jika kita ingin mengambil data berdasarkan **label atau nama kolomnya**.

Dengan menggunakan kedua metode ini, kita bisa memilih baris tunggal, rentang baris, hingga kolom-kolom tertentu dengan sangat fleksibel.

In [7]:
print("Baris pertama (posisi 0):")
display(df_ev.iloc[0])

print("\nBaris ke-2 sampai ke-4:")
display(df_ev.iloc[1:4])

print("\nKolom City dan Make untuk 5 baris pertama:")
display(df_ev.loc[0:4, ['City', 'Make']])

Baris pertama (posisi 0):

VIN (1-10)                                                                              1N4AZ0CP6D
County                                                                                        King
City                                                                                      Kirkland
State                                                                                           WA
Postal Code                                                                                98034.0
Model Year                                                                                    2013
Make                                                                                        NISSAN
Model                                                                                         LEAF
Electric Vehicle Type                                               Battery Electric Vehicle (BEV)
Clean Alternative Fuel Vehicle (CAFV) Eligibility          Clean Alternative Fuel Vehicle Eligible
Electric Range                                                                                75.0
Legislative District                                                                           1.0
DOL Vehicle ID                                                                           154635729
Vehicle Location                                                       POINT (-122.22901 47.72201)
Electric Utility                                     PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA)
2020 Census Tract                                                                    53033022203.0
Name: 0, dtype: object

Baris ke-2 sampai ke-4:

,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Legislative District,DOL Vehicle ID,Vehicle Location,Electric Utility,2020 Census Tract
1,5YJ3E1EC8L,Kitsap,Bainbridge Island,WA,98110.0,2020,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,308.0,23.0,107518645,POINT (-122.521 47.62759),PUGET SOUND ENERGY INC,5.303509e+10
2,5YJ3E1EBXJ,King,Seattle,WA,98144.0,2018,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,215.0,37.0,474808813,POINT (-122.30866 47.57874),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303301e+10
3,ZFAFFAC45R,Thurston,Yelm,WA,98597.0,2024,FIAT,500E,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,2.0,273658514,POINT (-122.60735 46.94239),PUGET SOUND ENERGY INC,5.306701e+10

Kolom City dan Make untuk 5 baris pertama:

                City    Make
0           Kirkland  NISSAN
1  Bainbridge Island   TESLA
2            Seattle   TESLA
3               Yelm    FIAT
4               Kent   TESLA

## Selecting Rows Based on Conditions

Sering kali kita tidak membutuhkan seluruh isi dataset. Kita mungkin hanya ingin menganalisis data yang memenuhi kriteria tertentu. Di Pandas, kita bisa melakukan penyaringan (filtering) dengan memberikan kondisi logika di dalam tanda kurung siku `[]`.

Misalnya, kita ingin mencari semua kendaraan listrik yang diproduksi oleh **TESLA** dan berada di kota **Seattle**. Kita juga bisa menggabungkan beberapa kondisi menggunakan operator logika seperti `&` (dan) atau `|` (atau).

In [8]:
df_tesla_only = df_ev[df_ev['Make'] == 'TESLA']
print(f"Jumlah mobil Tesla: {len(df_tesla_only)}")

df_filtered = df_ev[(df_ev['Make'] == 'TESLA') &
                    (df_ev['City'] == 'Seattle') &
                    (df_ev['Model Year'] >= 2022)]

print("\nHasil Filter (Tesla, Seattle, >= 2022):")
display(df_filtered.head())

Jumlah mobil Tesla: 114817

Hasil Filter (Tesla, Seattle, >= 2022):

,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Legislative District,DOL Vehicle ID,Vehicle Location,Electric Utility,2020 Census Tract
427,7SAYGDEE3N,King,Seattle,WA,98112.0,2022,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,37.0,269512400,POINT (-122.30207 47.64085),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303301e+10
483,7SAYGAEE4S,King,Seattle,WA,98133.0,2025,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,46.0,278164428,POINT (-122.33364 47.73709),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303300e+10
512,5YJ3E1EB8N,King,Seattle,WA,98133.0,2022,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,46.0,205841142,POINT (-122.33364 47.73709),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303300e+10
566,5YJ3E1EA1S,King,Seattle,WA,98178.0,2025,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,37.0,277022000,POINT (-122.25031 47.49481),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303301e+10
629,5YJ3E1EB8N,King,Seattle,WA,98122.0,2022,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,37.0,196589886,POINT (-122.31009 47.60803),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303301e+10

## Renaming Columns

Agar kode kita lebih bersih dan mudah dibaca, kita sering kali perlu mengganti nama kolom yang ada di DataFrame. Misalnya, kita bisa menyingkat nama kolom yang terlalu panjang atau menyeragamkan format penulisannya. Di Pandas, kita menggunakan metode `rename` dengan bantuan *dictionary* untuk memetakan nama kolom lama ke nama kolom yang baru.

In [9]:
df_renamed = df_ev.rename(columns={'Model Year': 'Year',
                                   'Electric Vehicle Type': 'EV_Type'})

print("Data dengan nama kolom yang sudah kita ganti:")
display(df_renamed[['City', 'Make', 'Year', 'EV_Type']].head())

Data dengan nama kolom yang sudah kita ganti:

                City    Make  Year                         EV_Type
0           Kirkland  NISSAN  2013  Battery Electric Vehicle (BEV)
1  Bainbridge Island   TESLA  2020  Battery Electric Vehicle (BEV)
2            Seattle   TESLA  2018  Battery Electric Vehicle (BEV)
3               Yelm    FIAT  2024  Battery Electric Vehicle (BEV)
4               Kent   TESLA  2020  Battery Electric Vehicle (BEV)

## Finding Unique Values and Their Counts

Dalam analisis data, kita sering kali ingin tahu berapa banyak kategori unik yang ada dalam suatu kolom dan berapa frekuensi kemunculannya. Hal ini sangat membantu kita untuk memahami distribusi data—misalnya, merek mobil apa yang paling banyak digunakan di dataset ini. Kita bisa menggunakan fungsi `value_counts()` untuk mendapatkan ringkasan ini secara instan.

In [10]:
print("Top 10 Merek Mobil Listrik Terbanyak:")
print(df_ev['Make'].value_counts().head(10))

print("\nTop 5 Kota dengan Mobil Listrik Terbanyak:")
print(df_ev['City'].value_counts().head(5))

Top 10 Merek Mobil Listrik Terbanyak:
Make
TESLA         114817
CHEVROLET      19410
NISSAN         16153
FORD           15423
KIA            14101
TOYOTA         11979
BMW            11647
HYUNDAI        10578
RIVIAN          8950
VOLKSWAGEN      7509
Name: count, dtype: int64

Top 5 Kota dengan Mobil Listrik Terbanyak:
City
Seattle      43219
Bellevue     13707
Vancouver    10444
Redmond       9642
Bothell       9297
Name: count, dtype: int64

## Handling Missing Values

Data yang hilang adalah masalah umum dalam analisis data. Kita punya dua strategi utama untuk mengatasinya:
1. **Menghapus (Deleting):** Jika jumlah data yang hilang sedikit, kita bisa menghapus baris tersebut.
2. **Mengisi (Imputing):** Kita bisa mengisi nilai yang kosong dengan nilai lain, misalnya rata-rata (mean), median, atau nilai yang paling sering muncul (mode).

Di Pandas, kita menggunakan `isnull()` untuk mendeteksi data kosong dan `dropna()` atau `fillna()` untuk menanganinya.

In [11]:
print("Jumlah data kosong per kolom:")
print(df_ev.isnull().sum())

df_clean = df_ev.dropna()
df_filled = df_ev.copy()
df_filled['Legislative District'] = df_filled['Legislative District'].fillna(0)

print(f"\nJumlah baris sebelum dibersihkan: {len(df_ev)}")
print(f"Jumlah baris setelah dropna: {len(df_clean)}")

Jumlah data kosong per kolom:
VIN (1-10)                                             0
County                                                12
City                                                  12
State                                                  0
Postal Code                                           12
Model Year                                             0
Make                                                   0
Model                                                  0
Electric Vehicle Type                                  0
Clean Alternative Fuel Vehicle (CAFV) Eligibility      0
Electric Range                                        12
Legislative District                                 703
DOL Vehicle ID                                         0
Vehicle Location                                      20
Electric Utility                                      12
2020 Census Tract                                     12
dtype: int64

Jumlah baris sebelum dibersihkan: 280833
Jumlah baris setelah dropna: 280110